=== FerdiandPH/JD2018-03-22/src/by/it/lyukovich/jd_02_07/Books.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT Books (Book+)>
<!ELEMENT Book (BookSysInfo+, BookLanguage, BookName, BookAuthors+, BookCountry, BookDescription, BookFileName, BookImgName, BookFormat, BookBuyInfo+)>
        <!ELEMENT BookSysInfo (BookID, BookCategoryID, BookDateUploaded)>
            <!ELEMENT BookID (#PCDATA)>
            <!ELEMENT BookCategoryID (#PCDATA)>
            <!ELEMENT BookDateUploaded (#PCDATA)>
        <!ELEMENT BookLanguage (#PCDATA)>
        <!ELEMENT BookName (#PCDATA)>
            <!ELEMENT BookAuthors (BookAuthor+)>
                <!ELEMENT BookAuthor (AuthorID, AuthorName, AuthorCountry)>
                    <!ELEMENT AuthorID (#PCDATA)>
                    <!ELEMENT AuthorName (#PCDATA)>
                    <!ELEMENT AuthorCountry (#PCDATA)>
        <!ELEMENT BookCountry (#PCDATA)>
        <!ELEMENT BookDescription (#PCDATA)>
        <!ELEMENT BookFileName (#PCDATA)>
        <!ELEMENT BookImgName (#PCDATA)>
        <!ELEMENT BookFormat (#PCDATA)>
        <!ELEMENT BookBuyInfo (BookBuyLink, BookPrice)>
        <!ELEMENT BookBuyLink (#PCDATA)>
        <!ELEMENT BookPrice (#PCDATA)>
        <!ATTLIST BookPrice curency CDATA "$">

=== FerdiandPH/JD2018-03-22/src/by/it/lyukovich/jd_02_07/Books+DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Books SYSTEM "Books.dtd">
<Books>
    <Book>
        <BookSysInfo>
            <BookID>1</BookID>
            <BookCategoryID>1</BookCategoryID>
            <BookDateUploaded>20.05.2018</BookDateUploaded>
        </BookSysInfo>
        <BookLanguage>English</BookLanguage>
        <BookName>Java The Complete Reference Ninth Edition</BookName>
        <BookAuthors>
            <BookAuthor>
                <AuthorID>1</AuthorID>
                <AuthorName>Herbert Shildt</AuthorName>
                <AuthorCountry>USA</AuthorCountry>
            </BookAuthor>
        </BookAuthors>
        <BookCountry>USA</BookCountry>
        <BookDescription>This edition of the book contains a substantial amount of
            new material because Java SE 8 adds several new features to the Java language.</BookDescription>
        <BookFileName>\books\1.zip</BookFileName>
        <BookImgName>\books\images\1.jpg</BookImgName>
        <BookFormat>PDF</BookFormat>
        <BookBuyInfo>
            <BookBuyLink><![CDATA[https://www.amazon.com/Java-Complete-Reference-Herbert-Schildt/dp/0071808558/ref=sr_1_4?ie=UTF8&qid=1527511896&sr=8-4&keywords=schildt+java]]></BookBuyLink>
            <BookPrice>36.87</BookPrice>
        </BookBuyInfo>
    </Book>

    <Book>
        <BookSysInfo>
            <BookID>2</BookID>
            <BookCategoryID>1</BookCategoryID>
            <BookDateUploaded>20.05.2018</BookDateUploaded>
        </BookSysInfo>
        <BookLanguage>English</BookLanguage>
        <BookName>Effective Java (3rd Edition)</BookName>
        <BookAuthors>
            <BookAuthor>
                <AuthorID>2</AuthorID>
                <AuthorName>Joshua Bloch</AuthorName>
                <AuthorCountry>USA</AuthorCountry>
            </BookAuthor>
        </BookAuthors>
        <BookCountry>USA</BookCountry>
        <BookDescription>Java has changed dramatically since the previous edition
            of Effective Java was published shortly after the release of Java 6.
            This Jolt award-winning classic has now been thoroughly updated to take
            full advantage of the latest language and library features. The support
            in modern Java for multiple paradigms increases the need for
            specific best-practices advice, and this book delivers.</BookDescription>
        <BookFileName>\books\2.zip</BookFileName>
        <BookImgName>\books\images\2.jpg</BookImgName>
        <BookFormat>PDF</BookFormat>
        <BookBuyInfo>
            <BookBuyLink><![CDATA[https://www.amazon.com/Effective-Java-3rd-Joshua-Bloch/dp/0134685997/ref=sr_1_1?s=books&ie=UTF8&qid=1527512394&sr=1-1&keywords=bloch+java]]></BookBuyLink>
            <BookPrice>23.99</BookPrice>
        </BookBuyInfo>
    </Book>
</Books>
